# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "434bcb44100e00accc3d41c1925529a8"
name = "refund-portal"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_orders,read_customers,write_customers,read_orders,write_orders, customer_write_customers"

# Protected customer data access for Customer Account API
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
